# Generated by Django 6.0.1 on 2026-02-01 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de la clase')),
                ('descripcion', models.TextField(verbose_name='descripcion de la clase')),
                ('horario', models.DateTimeField(verbose_name='horario de la clase')),
                ('duracion', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duracion en minutos')),
                ('capacidad_maxima', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidad maxima de la clase')),
                ('activa', models.BooleanField(default=True, help_text='Si está disponible para reservar', verbose_name='activa')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(limit_choices_to={'role': 'ENTRENADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='clases_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
